spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/productdb?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 3000
mybatis:
  mapper-locations: classpath:mapper/*.xml



